#!bin#bash

# rbenv Install

brew install rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> ~/.bash_profile
brew install ruby-build
brew install rbenv-gemset
brew install rbenv-gem-rehash
source ~/.bash_profile 


# rbenvの更新
念の為、やっておきましょう。

rm -rf ~/.rbenv/plugins/ruby-build
git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build


# 開発用ツールインストール
念の為、やっておきましょう

brew install readline
※ xcode 4.2.1 〜 gccが別のものになっているので以下コマンドを実行する。
brew search gcc
brew tap homebrew/dupes
brew install apple-gcc42

